user  root;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
  worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

  access_log  /var/log/nginx/access.log  main;

  sendfile        on;
  tcp_nopush      on;
  keepalive_timeout  65;
  gzip             on;
  gzip_min_length  1k;
  gzip_types       text/plain application/javascript text/css application/json application/xml;

  server {
    listen       5173;
    server_name  47.96.66.16;

    location / {
      root   /usr/share/nginx/html/frontend;
      index  index.html;
      try_files $uri $uri/ /index.html;
      add_header Cache-Control "no-cache, no-store, must-revalidate";  # 避免缓存问题
    }

    location /api/ {
      proxy_pass http://obe-backend:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      client_max_body_size 50m;
    }
  }
}